"""empty message

Revision ID: 52263ecb7b0b
Revises: df47a5ea5eec
Create Date: 2019-02-24 17:22:48.691402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52263ecb7b0b'
down_revision = 'df47a5ea5eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_num')
    # ### end Alembic commands ###
